# Generated by Django 3.0.4 on 2020-03-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_vendedor', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('usuarios_id_usuario', models.IntegerField()),
                ('foto', models.ImageField(blank=True, upload_to='administradores')),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BandejaEntrada',
            fields=[
                ('id_dashboard', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tabla_impresiones', models.IntegerField()),
                ('tabla_clics', models.IntegerField()),
                ('tabla_ctr', models.IntegerField()),
                ('tabla_costo', models.IntegerField()),
                ('anual', models.IntegerField()),
                ('mensual', models.IntegerField()),
                ('semanal', models.IntegerField()),
                ('diario', models.IntegerField()),
            ],
            options={
                'db_table': 'bandeja_entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nro_telefono', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_whatsapp', models.CharField(max_length=30)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_documento', models.CharField(max_length=15)),
                ('nro_documento', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, upload_to='vendedores')),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionDashboard',
            fields=[
                ('id_dashboard', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tabla_impresiones', models.IntegerField()),
                ('tabla_clics', models.IntegerField()),
                ('tabla_ctr', models.IntegerField()),
                ('tabla_costo', models.IntegerField()),
                ('anual', models.IntegerField()),
                ('mensual', models.IntegerField()),
                ('semanal', models.IntegerField()),
                ('diario', models.IntegerField()),
            ],
            options={
                'db_table': 'configuracion_dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('texto_mensaje', models.TextField()),
                ('tipo_mensaje', models.CharField(max_length=1)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('texto_nota', models.TextField()),
                ('tipo_nota', models.CharField(max_length=1)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'nota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=20)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(blank=True, upload_to='productos')),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('contrasenia', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, upload_to='usuarios')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='vendedores')),
            ],
            options={
                'db_table': 'vendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('forma_pago', models.CharField(max_length=1)),
                ('tipo_comprobante', models.CharField(max_length=1)),
                ('nro_comprobante', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
